CREATE TABLE IF NOT EXISTS purchase (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    category VARCHAR(255) NOT NULL,
    price DECIMAL(19, 2) NOT NULL,
    created TIME(6) NOT NULL,
    payment VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL
);
